### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by xj361685640** [holgerschmitz/Schnek#17]
Dear Holger Schmitz,

There is a compile error when I use this command
./configure
make

Here is the error message:

variables/function_expression.cpp: In function 'void schnek::registerCMath(schnek::FunctionRegistry&)':
variables/function_expression.cpp:34:35: error: no matching function for call to 'schnek::FunctionRegistry::registerFunction(const char [4], <unresolved overloaded function type>)'
   freg.registerFunction("cos", cos);
                                   ^
In file included from variables/function_expression.cpp:27:0:
variables/function_expression.hpp:230:10: note: candidate: template<class func> void schnek::FunctionRegistry::registerFunction(std::string, func)
     void registerFunction(std::string fname, func f)
          ^~~~~~~~~~~~~~~~
variables/function_expression.hpp:230:10: note:   template argument deduction/substitution failed:
variables/function_expression.cpp:34:35: note:   couldn't deduce template parameter 'func'
   freg.registerFunction("cos", cos);
                                   ^
How can I fix it?

Best regards,
Jie Xu

**Comment by holgerschmitz** [comment]
Apologies for the late reply.
The reason for the error originates from the fact that there are multiple overloaded `cos` function defined in the `<cmath>` header. Schnek can't cope with overloaded functions. You have to explicitly pick the function that you want. Look at the implementation of `registerCMath` in `src/variables/function_expression.cpp`. You will see that here the `double` version of `cos` is registered.

`freg.registerFunction("cos", static_cast<double (*)(double)>(cos));`
